services:
  - type: web
    name: cars-seller
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: cars-seller-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
